### ISSUE TITLE
Archived releases lack .jar files

### ISSUE THREAD

**Issue by katieltaylor** [mrmaxent/Maxent#1]
I noticed your archived releases all lack the .jar flies required to run the old versions, it looks like your .gitignore file says to exclude .jar files, is this on purpose?

**Comment by mrmaxent** [comment]
Thanks very much for noticing that.  I edited .gitignore, so now the 
.jar files are back with the old versions.


-- Steven

**Comment by bernibra** [comment]
The archived releases still lack the .jar files
