### ISSUE TITLE
Link to download points to 3.4.0 

### ISSUE THREAD

**Issue by veroandreo** [mrmaxent/Maxent#5]
Hello ,

The link to download maxent from here: https://biodiversityinformatics.amnh.org/open_source/maxent/ says current version 3.4.1, but the readme in the zip file still says 3.4.0. So, is it a matter of wrong link or old readme?

Thanks in advance!

**Comment by persts** [comment]
It is just an old readme. The app displays 3.4.1.

Here is the diff between the readme in the zip and the one in the repo:
```bash
10c10
< Version 3.4.0, December 2016
---
> Version 3.4.1, April 2017
120a121,125
> Main Changes in Version 3.4.1:
> -----------------------------
>    Fixed bug that caused regularization multiplier to be have increasing effect over multiple runs
> 
> 
```

**Comment by veroandreo** [comment]
Ok, good to know. Thanks for your prompt answer :)
I will close the issue then.
