### ISSUE TITLE
Link to download the new version of Maxent seems broken

### ISSUE THREAD

**Issue by bernibra** [mrmaxent/Maxent#6]
The link seems broken when I try to download the new version of Maxent from https://biodiversityinformatics.amnh.org/open_source/maxent/. If I instead clone the repository, the maxent.jar file is missing. Am I missing something obvious?

Thanks in advance for the help.

**Comment by persts** [comment]
@bernibra try the download link again.

**Comment by bernibra** [comment]
That sorted it! Cheers
